let selectedRole=localStorage.getItem('workwise-role')||'freelancer';
let accountMode='signin';
const loginPage=document.getElementById('loginPage');
const employerPage=document.getElementById('employerPage');
const loginForm=document.getElementById('loginForm');
const roleOptions=[...document.querySelectorAll('.role-option')];

function setRole(role){selectedRole=role;roleOptions.forEach(button=>button.classList.toggle('active',button.dataset.role===role))}
function hideAccountViews(){loginPage.hidden=true;employerPage.hidden=true;document.getElementById('communityPage').hidden=true;document.querySelector('.welcome').hidden=true;document.querySelector('.search-panel').hidden=true;document.querySelector('.content-grid').hidden=true}
function showLogin(role=selectedRole){hideAccountViews();setRole(role);loginPage.hidden=false;document.getElementById('communityNav').classList.remove('active');document.getElementById('savedNav').classList.remove('active');document.querySelector('.nav-link:first-child').classList.remove('active');document.getElementById('hireNav').classList.toggle('active',role==='employer')}
function showFreelancerArea(user){hideAccountViews();document.querySelector('.welcome').hidden=false;document.querySelector('.search-panel').hidden=false;document.querySelector('.content-grid').hidden=false;document.querySelector('.nav-link:first-child').classList.add('active');document.getElementById('communityNav').classList.remove('active');document.getElementById('hireNav').classList.remove('active');const name=user?.name||localStorage.getItem('workwise-user-name')||'Jamie Davis';const initials=name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'JD';localStorage.setItem('workwise-user-name',name);localStorage.setItem('workwise-user-initials',initials);document.getElementById('accountName').textContent=name;document.querySelector('#accountButton .avatar').textContent=initials;document.querySelector('.mini-profile strong').textContent=name;document.querySelector('.avatar.large').textContent=initials;apiRequest('/api/profile').then(renderProfile).catch(()=>{})}
function renderProfile(profileData){const name=profileData.name||'Workwise member';const profile=profileData.profile||{};const initials=name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'WM';document.getElementById('accountName').textContent=name;document.querySelector('#accountButton .avatar').textContent=initials;document.getElementById('profileAvatar').textContent=initials;document.getElementById('profileDisplayName').textContent=name;document.getElementById('profileDisplayTitle').textContent=profile.title||'Add a professional title';const location=document.getElementById('profileDisplayLocation');location.textContent=profile.location||'';location.hidden=!profile.location;const portfolio=document.getElementById('profilePortfolioPreview');portfolio.href=profile.portfolioUrl||'#';portfolio.hidden=!profile.portfolioUrl;const bio=document.getElementById('profileBioPreview');bio.textContent=profile.bio||'';bio.hidden=!profile.bio;const tags=document.getElementById('profileSkillPreview');tags.replaceChildren();(profile.skills||[]).forEach(skill=>{const tag=document.createElement('span');tag.textContent=skill;tags.append(tag)});const strength=Math.min(100,(name?10:0)+(profile.title?20:0)+(profile.location?10:0)+(profile.bio?25:0)+(profile.skills?.length?25:0)+(profile.portfolioUrl?10:0));document.getElementById('profileStrength').textContent=`${strength}%`;document.getElementById('profileTopStrength').textContent=`${strength}%`;document.getElementById('profileProgressBar').style.width=`${strength}%`;localStorage.setItem('workwise-user-name',name);localStorage.setItem('workwise-user-initials',initials)}
async function openProfileEditor(){try{const data=await apiRequest('/api/profile');const profile=data.profile||{};document.getElementById('profileNameInput').value=data.name||'';document.getElementById('profileTitleInput').value=profile.title||'';document.getElementById('profileLocationInput').value=profile.location||'';document.getElementById('profileBioInput').value=profile.bio||'';document.getElementById('profileSkillsInput').value=(profile.skills||[]).join(', ');document.getElementById('profilePortfolioInput').value=profile.portfolioUrl||'';showProfileError('');document.getElementById('profileDialog').showModal()}catch(error){if(error.message.includes('Sign in'))showLogin(selectedRole);else showToast(error.message)}}
function showProfileError(message){const node=document.getElementById('profileFormError');node.textContent=message||'';node.hidden=!message}
function showEmployerArea(user){hideAccountViews();employerPage.hidden=false;document.querySelectorAll('.nav-link').forEach(link=>link.classList.remove('active'));document.getElementById('hireNav').classList.add('active');if(user){localStorage.setItem('workwise-user-name',user.name);localStorage.setItem('workwise-user-initials',user.name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase())}document.getElementById('accountName').textContent=localStorage.getItem('workwise-user-name')||'Employer';document.querySelector('#accountButton .avatar').textContent=localStorage.getItem('workwise-user-initials')||'EM';renderPostedJobs();apiRequest('/api/profile').then(renderProfile).catch(()=>{})}
function showAccountError(message){const node=document.getElementById('accountError');node.textContent=message||'';node.hidden=!message}
async function apiRequest(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The request could not be completed.');return result}
async function openRoleWorkspace(role){try{const user=await apiRequest('/api/auth/me');if(user.role!==role){showLogin(role);return}setRole(role);role==='employer'?showEmployerArea(user):showFreelancerArea(user)}catch{showLogin(role)}}
async function renderPostedJobs(){let posted=[],received=[];try{[posted,received]=await Promise.all([apiRequest('/api/employer/jobs'),apiRequest('/api/employer/applications')])}catch{try{posted=JSON.parse(localStorage.getItem('workwise-employer-jobs')||'[]');received=JSON.parse(localStorage.getItem('workwise-applications')||'[]')}catch{}}
  const ownIds=new Set(posted.map(job=>String(job.id)));received=received.filter(application=>ownIds.has(String(application.jobId)));document.getElementById('employerJobCount').textContent=posted.length;document.getElementById('employerProposalCount').textContent=received.length;
  const container=document.getElementById('postedJobs');container.replaceChildren();if(!posted.length){const empty=document.createElement('div');empty.className='posted-empty';empty.textContent='Your published jobs will appear here.';container.append(empty)}else posted.slice().reverse().forEach(job=>{const card=document.createElement('article');card.className='posted-job';const title=document.createElement('strong');title.textContent=job.title;const meta=document.createElement('span');meta.textContent=`${job.category} · ${job.type} · ${job.budget}`;const status=document.createElement('span');status.className='job-status';status.textContent='Published';const count=received.filter(application=>String(application.jobId)===String(job.id)).length;const proposals=document.createElement('span');proposals.className='proposal-count';proposals.textContent=`${count} ${count===1?'proposal':'proposals'}`;card.append(title,meta,status,proposals);container.append(card)});
  const proposalContainer=document.getElementById('employerProposals');proposalContainer.replaceChildren();if(!received.length){const empty=document.createElement('div');empty.className='posted-empty';empty.textContent='Applications for your jobs will appear here.';proposalContainer.append(empty);return}received.slice().reverse().slice(0,8).forEach(application=>{const card=document.createElement('article');card.className='employer-proposal';const applicant=document.createElement('strong');applicant.textContent=application.applicantName;const details=document.createElement('div');details.className='proposal-job';details.textContent=`${application.jobTitle} · ${application.rate}`;const letter=document.createElement('p');letter.textContent=application.coverLetter;card.append(applicant,details,letter);const files=document.createElement('div');files.className='proposal-files';for(const kind of ['resume','coverPhoto']){const name=application.attachments?.[kind];if(!name)continue;const link=document.createElement('a');link.className='proposal-file';link.textContent=`↓ ${name}`;link.href=`/api/applications/${encodeURIComponent(application.id)}/attachments/${kind}`;link.download=name;files.append(link)}card.append(files);proposalContainer.append(card)})
}
function addToMarketplace(job){const client=job.client||'Workwise client',level=(job.level||'Intermediate').replace(' level',''),existing=jobs.find(item=>String(item.id)===String(job.id));const mapped={id:job.id,company:client,initial:client.slice(0,1).toUpperCase(),logo:existing?.logo||7,title:job.title,rating:job.rating||existing?.rating||'New client',verified:Boolean(job.verified),desc:job.description||existing?.desc||'',tags:job.tags?.length?job.tags:existing?.tags||[job.category,level+' level'],type:(job.type||'Fixed price').toLowerCase()==='hourly'?'hourly':'fixed',pay:job.budget||existing?.pay||'',level,duration:job.duration||existing?.duration||'Project duration TBD',proposals:job.proposals||'0',posted:0,client:existing?.client||'Workwise',budget:Number(String(job.budget||existing?.budget||'').replace(/[^0-9.]/g,''))||0};if(existing)Object.assign(existing,mapped);else jobs.push(mapped)}

roleOptions.forEach(button=>button.addEventListener('click',()=>setRole(button.dataset.role)));
document.getElementById('accountModeToggle').addEventListener('click',event=>{accountMode=accountMode==='signin'?'register':'signin';const registering=accountMode==='register';document.getElementById('modePrompt').textContent=registering?'Already have an account?':'New to Workwise?';event.currentTarget.textContent=registering?'Sign in':'Create an account';document.getElementById('fullNameField').hidden=!registering;document.getElementById('loginName').required=registering;document.getElementById('loginPassword').autocomplete=registering?'new-password':'current-password';document.getElementById('accountSubmit').innerHTML=registering?'Create account <span>↗</span>':'Sign in <span>↗</span>';document.getElementById('forgotPassword').hidden=registering;showAccountError('')});
document.getElementById('hireNav').addEventListener('click',event=>{event.preventDefault();openRoleWorkspace('employer')});
document.getElementById('accountButton').addEventListener('click',async()=>{try{const user=await apiRequest('/api/auth/me');if(user.role==='employer')showEmployerArea(user);else showLogin(user.role)}catch{showLogin(selectedRole)}});
document.getElementById('loginBack').addEventListener('click',()=>showFreelancerArea());
document.getElementById('forgotPassword').addEventListener('click',event=>{event.preventDefault();showToast('Contact your Workwise administrator to reset a password.')});
loginForm.addEventListener('submit',async event=>{event.preventDefault();if(!loginForm.reportValidity())return;const submit=document.getElementById('accountSubmit');submit.disabled=true;showAccountError('');try{const registering=accountMode==='register';const body={email:document.getElementById('loginEmail').value.trim(),password:document.getElementById('loginPassword').value,role:selectedRole};if(registering)body.name=document.getElementById('loginName').value.trim();const user=await apiRequest(registering?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(body)});localStorage.setItem('workwise-role',user.role);if(user.role==='employer')showEmployerArea(user);else showFreelancerArea(user)}catch(error){showAccountError(error.message)}finally{submit.disabled=false}});
document.getElementById('switchRole').addEventListener('click',async()=>{try{await apiRequest('/api/auth/logout',{method:'POST'});localStorage.removeItem('workwise-role');showFreelancerArea()}catch{showToast('Could not sign out. Please try again.')}});
document.getElementById('postJobForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const job={title:document.getElementById('postTitle').value.trim(),category:document.getElementById('postCategory').value,level:document.getElementById('postLevel').value,description:document.getElementById('postDescription').value.trim(),type:document.getElementById('postType').value,budget:document.getElementById('postBudget').value.trim(),tags:[document.getElementById('postCategory').value]};try{await apiRequest('/api/jobs',{method:'POST',body:JSON.stringify(job)});form.reset();await refreshMarketplaceJobs();await renderPostedJobs();showToast('Your job has been published')}catch(error){showToast(error.message)}});
async function refreshMarketplaceJobs(){try{const response=await fetch('/api/jobs',{credentials:'same-origin'});if(!response.ok)throw new Error('Could not load posted jobs.');const serverJobs=await response.json();if(response.headers.get('X-Workwise-Seeds-Initialized')==='true'){const liveSeedIds=new Set(serverJobs.filter(job=>job.kind==='seed').map(job=>String(job.id)));for(let index=jobs.length-1;index>=0;index--){if(Number(jobs[index].id)>=1&&Number(jobs[index].id)<=8&&!liveSeedIds.has(String(jobs[index].id)))jobs.splice(index,1)}}serverJobs.forEach(addToMarketplace);render()}catch(error){console.warn('Could not load posted jobs from the server:',error.message)}}
refreshMarketplaceJobs();
if(localStorage.getItem('workwise-user-name')){document.getElementById('accountName').textContent=localStorage.getItem('workwise-user-name');document.querySelector('#accountButton .avatar').textContent=localStorage.getItem('workwise-user-initials')||'JD'}
document.getElementById('profileBtn').addEventListener('click',openProfileEditor);
document.getElementById('employerEditProfile').addEventListener('click',openProfileEditor);
document.getElementById('editProfile').addEventListener('click',event=>{event.preventDefault();openProfileEditor()});
document.getElementById('profileDisplayName').addEventListener('click',openProfileEditor);
document.getElementById('tipLink').addEventListener('click',event=>{event.preventDefault();openProfileEditor()});
document.getElementById('closeProfileDialog').addEventListener('click',()=>document.getElementById('profileDialog').close());
document.getElementById('cancelProfileEdit').addEventListener('click',()=>document.getElementById('profileDialog').close());
document.getElementById('profileEditForm').addEventListener('submit',async event=>{event.preventDefault();const button=document.getElementById('saveProfileButton');button.disabled=true;showProfileError('');const body={name:document.getElementById('profileNameInput').value.trim(),profile:{title:document.getElementById('profileTitleInput').value.trim(),location:document.getElementById('profileLocationInput').value.trim(),bio:document.getElementById('profileBioInput').value.trim(),skills:document.getElementById('profileSkillsInput').value.split(',').map(skill=>skill.trim()).filter(Boolean),portfolioUrl:document.getElementById('profilePortfolioInput').value.trim()}};try{const updated=await apiRequest('/api/profile',{method:'PATCH',body:JSON.stringify(body)});renderProfile(updated);document.getElementById('profileDialog').close();showToast('Your profile has been saved')}catch(error){showProfileError(error.message)}finally{button.disabled=false}});
apiRequest('/api/profile').then(renderProfile).catch(()=>{});
