const communityContacts=[
  {id:'northstar',name:'Olivia Chen',company:'Northstar Studio',initial:'OC',tone:'logo-1',time:'10:42 AM',unread:true,messages:[{from:'them',text:'Hey Jamie! We loved your initial concepts. Could you share a little more about how you’d approach the onboarding flow?',time:'10:18 AM'},{from:'me',text:'Thanks, Olivia! I’d start by mapping the first-time user journey and identifying the moments where people need a bit more guidance.',time:'10:26 AM'},{from:'them',text:'That sounds great. We’re especially interested in keeping the experience calm and reassuring.',time:'10:42 AM'}]},
  {id:'sunday',name:'Marcus Reed',company:'Sunday Goods',initial:'MR',tone:'logo-2',time:'Yesterday',unread:false,messages:[{from:'them',text:'The packaging directions are looking really good. We’re leaning toward the warmer palette.',time:'Yesterday'},{from:'me',text:'Perfect, I’ll refine that direction and send over the next round tomorrow.',time:'Yesterday'}]},
  {id:'lumen',name:'Priya Shah',company:'Lumen Health',initial:'PS',tone:'logo-3',time:'Mon',unread:false,messages:[{from:'them',text:'Could we set up a quick call to walk through the audit findings?',time:'Monday'},{from:'me',text:'Absolutely. I’ll send a few times that work for me.',time:'Monday'}]},
  {id:'atlas',name:'Daniel Foster',company:'Atlas Commerce',initial:'DF',tone:'logo-4',time:'Sep 18',unread:false,messages:[{from:'them',text:'Thanks for sending the first draft. The direction feels right for the launch.',time:'Sep 18'}]},
  {id:'fieldwork',name:'Sofia Martinez',company:'Fieldwork',initial:'SM',tone:'logo-5',time:'Sep 16',unread:false,messages:[{from:'me',text:'I’ve added the component states and notes to the shared file.',time:'Sep 16'},{from:'them',text:'Got it, thank you! The documentation is super clear.',time:'Sep 16'}]}
];
let activeConversation=null;
try{const savedMessages=JSON.parse(localStorage.getItem('workwise-community-messages')||'{}');communityContacts.forEach(c=>{if(savedMessages[c.id]){c.messages=savedMessages[c.id].messages;c.time=savedMessages[c.id].time}})}catch{}
const communityPage=document.getElementById('communityPage'), communityShell=document.querySelector('.community-shell');
const getLatest=contact=>contact.messages[contact.messages.length-1]?.text||'Start a conversation';
function renderConversations(){const query=document.getElementById('conversationSearch').value.trim().toLowerCase();const filtered=communityContacts.filter(c=>(c.name+' '+c.company+' '+getLatest(c)).toLowerCase().includes(query));document.getElementById('conversationList').innerHTML=filtered.length?filtered.map(c=>`<button class="conversation-item ${activeConversation===c.id?'active':''}" data-contact="${c.id}"><span class="avatar ${c.tone}">${c.initial}</span><span class="conversation-item-copy"><span class="conversation-item-top"><strong>${c.name}</strong><time>${c.time}</time></span><p>${getLatest(c)}</p></span>${c.unread?'<i class="unread-dot" aria-label="Unread"></i>':''}</button>`).join(''):'<div class="chat-empty"><p>No conversations match your search.</p></div>';}
function renderChat(id){const c=communityContacts.find(x=>x.id===id);if(!c)return;activeConversation=id;c.unread=false;communityShell.classList.add('has-chat');document.getElementById('chatPanel').innerHTML=`<header class="chat-header"><button class="chat-back" id="chatBack" aria-label="Back to conversations">←</button><span class="avatar ${c.tone}">${c.initial}</span><span class="chat-person"><strong>${c.name}</strong><span><i class="online-dot"></i>${c.company} · Client</span></span><span class="chat-header-actions" aria-hidden="true">···</span></header><div class="chat-messages" id="chatMessages"><div class="message-date">TODAY</div>${c.messages.map(m=>`<div class="message-row ${m.from==='me'?'mine':''}">${m.from==='them'?`<span class="avatar ${c.tone}">${c.initial}</span>`:''}<div class="message-bubble">${escapeMessage(m.text)}</div><time class="message-time">${m.time}</time></div>`).join('')}</div><form class="chat-composer" id="chatComposer"><textarea id="messageInput" rows="1" placeholder="Write a message…" aria-label="Write a message"></textarea><button type="submit" id="sendMessage" disabled>Send ↗</button></form><div class="chat-note">Keep payments and project details on Workwise for a safer experience.</div>`;renderConversations();const messageInput=document.getElementById('messageInput'),sendButton=document.getElementById('sendMessage');messageInput.addEventListener('input',()=>{sendButton.disabled=!messageInput.value.trim()});messageInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.getElementById('chatComposer').requestSubmit()}});document.getElementById('chatComposer').addEventListener('submit',e=>{e.preventDefault();const text=messageInput.value.trim();if(!text)return;const now=new Date();const time=now.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});c.messages.push({from:'me',text,time});c.time=time;const savedState=JSON.parse(localStorage.getItem('workwise-community-messages')||'{}');savedState[c.id]={messages:c.messages,time:c.time};localStorage.setItem('workwise-community-messages',JSON.stringify(savedState));renderChat(c.id);document.getElementById('chatMessages').scrollTop=document.getElementById('chatMessages').scrollHeight;document.getElementById('messageInput').focus()});document.getElementById('chatBack').addEventListener('click',()=>{communityShell.classList.remove('has-chat')});const messages=document.getElementById('chatMessages');messages.scrollTop=messages.scrollHeight;}
function escapeMessage(value){const div=document.createElement('div');div.textContent=value;return div.innerHTML}
function showCommunity(){document.querySelector('.welcome').hidden=true;document.querySelector('.search-panel').hidden=true;document.querySelector('.content-grid').hidden=true;communityPage.hidden=false;document.getElementById('communityNav').classList.add('active');document.getElementById('savedNav').classList.remove('active');document.querySelector('.nav-link:first-child').classList.remove('active');communityShell.classList.remove('has-chat');renderConversations();}
function showJobs(){communityPage.hidden=true;document.querySelector('.welcome').hidden=false;document.querySelector('.search-panel').hidden=false;document.querySelector('.content-grid').hidden=false;document.getElementById('communityNav').classList.remove('active');document.querySelector('.nav-link:first-child').classList.add('active');}
document.getElementById('communityNav').addEventListener('click',e=>{e.preventDefault();showCommunity()});document.getElementById('backToJobs').addEventListener('click',showJobs);document.getElementById('conversationSearch').addEventListener('input',renderConversations);document.getElementById('conversationList').addEventListener('click',e=>{const item=e.target.closest('[data-contact]');if(item)renderChat(item.dataset.contact)});document.getElementById('newMessage').addEventListener('click',()=>{if(!communityContacts.length)return;renderChat(communityContacts[0].id);document.getElementById('messageInput').focus()});
